name: Rust
true:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: 'cargo check --verbose'
      - name: 'Run tests'
        run: 'cargo test --verbose'
  release:
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: 'cargo build --release'
      - name: 'Upload a Build Artifact'
        uses: actions/upload-artifact@v2
        with:
          path: target/release/cardgames*
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
